### ISSUE TITLE
Error on running buildAndRun script. 

### ISSUE THREAD

**Issue by mahajay** [BBVA/mirrorgate#3]
> node-sass@4.9.0 install /home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/node-sass
> node scripts/install.js

Unable to save binary /home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:874:3)
    at sync (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/node-sass/vendor' }

> wd@1.9.0 install /home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/wd
> node scripts/build-browser-scripts

/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/wd/build'
    at Object.fs.mkdirSync (fs.js:874:3)
    at sync (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
npm WARN mirrogate-dashboard@0.0.1 No repository field.
npm WARN mirrogate-dashboard@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.9.0 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wd@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by kdaimiel** [comment]
As I see it, you don't have enough permission to run the script. Try to run the script with sudo.

**Comment by alfonso-presa** [comment]
Additionally, seems like you're trying to start MirrorGate in a EC2 machine. I would recommend using docker to do so instead of using the buildAndRun script, which is meant for local development purposes.

Please check this point of the docs: https://github.com/BBVA/mirrorgate#running

If you have any further questions don't hesitate asking.

**Comment by mahajay** [comment]
I did try with sudo with the similar consequence (got "permission denied" error on some other directory). I was able to run it using docker, but I want to customize mirrorgate and that is why I am trying to run it standalone. I am using EC2 as I do not have linux machine and facing difficulties on my windows machine for local development.

**Comment by alfonso-presa** [comment]
Great you had the issue solved. May I ask what was the problem? It may help someone else (or our selves to try to avoid it).

**Comment by zeyangli** [comment]
这个问题应该是因为在npm打包的时候没有添加 --unsafe-perm=true 选项导致的。

**Comment by zeyangli** [comment]
还有一个选项  --allow-root 也需要加上。

**Comment by alfonso-presa** [comment]
@zeyangli Thank you for reporting back. Please now on, ensure to write in english only as we should be able to moderate this (even though we at this project are not english speakers either ;-) ). Thanks!
