### ISSUE TITLE
Error on gulpfile.js

### ISSUE THREAD

**Issue by mahajay** [BBVA/mirrorgate#5]
/home/ec2-user/mirrorgate/mirrorgate-dashboard/gulpfile.js:66
gulp.task('clean', () => gulp.src(paths.dist + "*", {read: false}).pipe(clean(
                    ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.execute (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/gulp/node_modules/liftoff/index.js:203:12)
    at module.exports (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/home/ec2-user/mirrorgate/mirrorgate-dashboard/node_modules/gulp/node_modules/liftoff/index.js:195:5)

**Comment by kdaimiel** [comment]
Would you mind to specify which version of node and gulp you are using and which command you are running?

**Comment by mahajay** [comment]
node - 0.10.48
gulp - ^3.9.1

**Comment by kdaimiel** [comment]
That's a very old version of node. We required nodejs >= 6. I recommend node 7.

**Comment by alfonso-presa** [comment]
No more news on this issue so I guess upgrading the node version heleped. Right?
