### ISSUE TITLE
The 'cursor' option is required, except for aggregate with the explain argument

### ISSUE THREAD

**Issue by lwasylow** [BBVA/mirrorgate#6]
Hi 
After running a mongo and mirrogate dockers (from readme files) and trying to save a dashboard I got an error :com.mongodb.MongoCommandException: Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server mongo:27017. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }
        at com.mongodb.CommandResult.getException(CommandResult.java:80) ~[mongodb-driver-3.4.2.jar!/:na]
        at com.mongodb.CommandResult.throwOnError(CommandResult.java:94) ~[mongodb-driver-3.4.2.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.handleCommandError(MongoTemplate.java:2097) ~[spring-data-mongodb-1.10.3.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1574) ~[spring-data-mongodb-1.10.3.RELEASE.jar!/:na]
        at org.springframework.data.mongodb.core.MongoTemplate.aggregate(MongoTemplate.java:1502) ~[spring-data-mongodb-1.10.3.RELEASE.jar!/:na]
        at com.bbva.arq.devops.ae.mirrorgate.repository.DashboardRepositoryImpl.getDashboardsNotInStatus(DashboardRepositoryImpl.java:85) ~[classes!/:na]
        at com.bbva.arq.devops.ae.mirrorgate.repository.DashboardRepositoryImpl.getActiveDashboards(DashboardRepositoryImpl.java:72) ~[classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:504) ~[spring-data-commons-1.13.3.RELEASE.jar!/:na]

**Comment by lwasylow** [comment]
Turn out that have to do download older mongo version. Tag 3.2 worked.

**Comment by kdaimiel** [comment]
Hi @lwasylow,

According to MongoDB 3.6 release note https://docs.mongodb.com/manual/reference/command/aggregate/ it is not possible to do aggregation queries without the cursor and the driver we use doesn't support it. We will consider to upgrade th e driver but until that, we recomend
